---
version: 2
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix(deps)"
      prefix-development: "chore(dev-deps)"
    groups:
      wasmtime-dependencies:
        patterns:
          - "wasmtime*"
      wit-bindgen-dependencies:
        patterns:
          - "wit-bindgen*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: /
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix(deps)"
      prefix-development: "chore(dev-deps)"