package jontze:function-http;

world function-http {
    /// Represents a general HTTP header, e.g. ("Content-Type", "application/json")
    record header {
        name: string,
        value: string,
    }

    /// Http Methods
    enum method {
        GET,
        POST,
        PUT,
        DELETE,
        PATCH,
        OPTIONS,
        HEAD,
    }

    /// Represents an inbound HTTP request to your serverless function.
    record request {
        method: method,        
        path: string,
        /// Key-value pairs representing the query parameters in the URL
        query-params: list<header>,
        /// Key-value pairs representing the request headers
        headers: list<header>,
        /// Raw request body bytes (could be JSON, form data, etc.)
        body: list<u8>,
    }

    record response {
        status-code: u16,        
        headers: list<header>,
        body: list<u8>,
    }

    export path: func() -> string;

    export handle-request: func(req: request) -> result<response>;
}
