{{- if empty .Values.wasmFunctionRuntime.database.existingSecretRef.name }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "wasm-function-runtime.fullname" . }}-database
  labels:
    {{- include "wasm-function-runtime.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.wasmFunctionRuntime.database.connectionString | b64enc }}
{{- end }}