{{- if and .Values.wasmFunctionRuntime.cache.redis.enabled (empty .Values.wasmFunctionRuntime.cache.redis.existingSecretRef.name) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "wasm-function-runtime.fullname" . }}-redis
  labels:
    {{- include "wasm-function-runtime.labels" . | nindent 4 }}
type: Opaque
data:
  REDIS_CONNECTION: {{ .Values.wasmFunctionRuntime.cache.redis.connectionString | b64enc }}
{{- end }}