{{- if .Values.wasmFunctionRuntime.storage.minio.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "wasm-function-runtime.fullname" . }}-storage-minio
  labels:
    {{- include "wasm-function-runtime.labels" . | nindent 4 }}
data:
  MINIO_ENDPOINT: {{ .Values.wasmFunctionRuntime.storage.minio.endpoint}}
  MINIO_BUCKET: {{ .Values.wasmFunctionRuntime.storage.minio.bucketName }}
{{- end }}