{{- if and .Values.wasmFunctionRuntime.storage.hetzner.enabled (empty .Values.wasmFunctionRuntime.storage.hetzner.existingSecretRef.name) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "wasm-function-runtime.fullname" . }}-storage-hetzner
  labels:
    {{- include "wasm-function-runtime.labels" . | nindent 4 }}
type: Opaque
data:
  HETZNER_BUCKET_ACCESS_KEY: {{ .Values.wasmFunctionRuntime.storage.hetzner.accessKey | b64enc }}
  HETZNER_BUCKET_ACCESS_SECRET_KEY: {{ .Values.wasmFunctionRuntime.storage.hetzner.secretKey | b64enc }}
{{- end }}