{{- if and .Values.wasmFunctionRuntime.storage.azure.enabled (empty .Values.wasmFunctionRuntime.storage.azure.existingSecretRef.name) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "wasm-function-runtime.fullname" . }}-storage-azure
  labels:
    {{- include "wasm-function-runtime.labels" . | nindent 4 }}
type: Opaque
data:
  AZURE_STORAGE_ACCOUNT_ACCESS_KEY: {{ .Values.wasmFunctionRuntime.storage.azure.storageAccountKey | b64enc }}
{{- end }}
