{{- if and .Values.wasmFunctionRuntime.storage.minio.enabled (empty .Values.wasmFunctionRuntime.storage.minio.existingSecretRef.name) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "wasm-function-runtime.fullname" . }}-storage-minio
  labels:
    {{- include "wasm-function-runtime.labels" . | nindent 4 }}
type: Opaque
data:
  MINIO_ACCESS_KEY: {{ .Values.wasmFunctionRuntime.storage.minio.accessKey | b64enc }}
  MINIO_SECRET_KEY: {{ .Values.wasmFunctionRuntime.storage.minio.secretKey | b64enc }}
{{- end }}