name: Chart Test
on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Helm Lint
        working-directory: chart/wasm-function-runtime
        run: helm lint

  template:
    name: Template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Default Template
        working-directory: chart/wasm-function-runtime
        run: helm template .
