name: Main
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    uses: jontze/.workflows/.github/workflows/rust_test.yaml@main
    with:
      build: true
      unit-tests: true

  push-image:
    needs:
      - test
    permissions:
      contents: read
      packages: write
    name: Publish Image
    uses: ./.github/workflows/image.yml
    with:
      image_name: "wasm-function-runtime"
      push: true
    secrets: inherit
