name: Main
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    uses: jontze/.workflows/.github/workflows/rust_test.yaml@main
    with:
      build: true
      unit-tests: true

  build-cli:
    needs:
      - test
    name: Build CLI
    uses: jontze/.workflows/.github/workflows/rust_platform_binaries.yaml@main
    with:
      name: "wasm-function-cli"
      version: "main"
    secrets: inherit

  push-image:
    if: false
    needs:
      - test
    permissions:
      contents: read
      packages: write
    name: Publish Image
    uses: jontze/.workflows/.github/workflows/image_publish.yaml@main
    with:
      image_name: "wasm-function-runtime"
      push: true
      cache_from_tag: "main"
    secrets: inherit
