name: PR
on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - "chart/**"

jobs:
  test:
    name: Test
    uses: jontze/.workflows/.github/workflows/rust_test.yaml@main
    with:
      build: true
      unit-tests: true
