name: Release
on:
  push:
    tags:
      - v*

env:
  RUST_BACKTRACE: full
  RUSTUP_MAX_RETRIES: 100
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 100
  CARGO_TERM_COLOR: always

jobs:
  build-cli:
    name: Build CLI
    uses: jontze/.workflows/.github/workflows/rust_platform_binaries.yaml@main
    with:
      name: "wasm-function-cli"
    secrets: inherit

  push-image:
    permissions:
      contents: read
      packages: write
    name: Publish Image
    uses: jontze/.workflows/.github/workflows/image_publish.yaml@main
    with:
      image_name: "wasm-function-runtime"
      push: true
      cache_from_tag: "main"
    secrets: inherit
